name: Jira CRUD

on:
  workflow_dispatch:
    inputs:

      ticket_id:
        description: "Jira Ticket ID"
        required: true

      operation:
        description: "Operation"
        required: true
        type: choice
        options:
          - read
          - validate
          - get_fields
          - status
          - update
          - create

      field_name:
        description: "Field Name"
        required: false

      field_value:
        description: "Field Value"
        required: false

jobs:

  jira:

    runs-on: ubuntu-latest

    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      TICKET_ID: ${{ github.event.inputs.ticket_id }}
      OPERATION: ${{ github.event.inputs.operation }}
      FIELD_NAME: ${{ github.event.inputs.field_name }}
      FIELD_VALUE: ${{ github.event.inputs.field_value }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          pip install -r requirements.txt

      - run: |
          python app/jira_runner.py
